# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
  - id: sam-validate
    name: SAM Validate
    entry: sam validate --template
    language: system
    types: [yaml]
    files: ^template(\.[^.]+)?\.ya?ml$
  - id: black
    name: black
    entry: black
    language: system
    types: [python]
  - id: isort
    name: isort
    entry: isort
    language: system
    types: [python]
    args: ["--profile", "black"]
  - id: flake8
    name: flake8
    entry: flake8
    language: system
    types: [python]
  - id: mypy
    name: mypy
    entry: mypy
    language: system
    types: [python]

  # - id: pytest
  #   name: pytest
  #   entry: bash -c "pytest"
  #   language: system
  #   stages: [pre-push]
  #   always_run: true
  #   pass_filenames: false
