version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - AWS_ENDPOINT_URL

  localstack:
    image: localstack/localstack:4.4
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,apigateway,s3,cloudformation,iam,logs,sqs,events
      - DEBUG=1
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - LAMBDA_EXECUTOR=local
      - DATA_DIR=/var/lib/localstack
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack_data:/var/lib/localstack

volumes:
  localstack_data:
