version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        http_proxy: ${http_proxy}
        HTTP_PROXY: ${HTTP_PROXY}
        https_proxy: ${https_proxy}
        HTTPS_PROXY: ${HTTPS_PROXY}
        no_proxy: ${no_proxy}
        NO_PROXY: ${NO_PROXY}
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - AWS_ENDPOINT_URL
      - BUCKET_NAME
      - OBJECT_NAME
      - QUEUE_NAME

      - http_proxy
      - HTTP_PROXY
      - https_proxy
      - HTTPS_PROXY
      - no_proxy
      - NO_PROXY
  localstack:
    image: localstack/localstack-pro:4.5
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,apigateway,s3,cloudformation,iam,logs,sqs,events,cloudwatch,ssm,rds,secretsmanager
      - DEBUG=1
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - LAMBDA_EXECUTOR=local
      - DATA_DIR=/var/lib/localstack
      - LOCALSTACK_AUTH_TOKEN

      - http_proxy
      - HTTP_PROXY
      - https_proxy
      - HTTPS_PROXY
      - no_proxy
      - NO_PROXY
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack_data:/var/lib/localstack

volumes:
  localstack_data:
