version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=ap-northeast-1
      - AWS_ENDPOINT_URL=http://localstack:4566

  localstack:
    image: localstack/localstack:3.3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,apigateway,s3
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=ap-northeast-1
      - LAMBDA_EXECUTOR=local
      - DATA_DIR=/var/lib/localstack
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack_data:/var/lib/localstack

volumes:
  localstack_data:
